### ISSUE TITLE
use of brackets for frontend modification of slick-2

### ISSUE THREAD

**Issue by chrismade** [auniverseaway/slick-2#19]
Chris, you said in your video https://www.youtube.com/watch?v=7EC1EdSs72U that bracket.io can be used in original AEM but cant in a pure sling instance - I guess that's also true then for slick-2 - can you please spend a few more words WHY it is not working ?

**Comment by auniverseaway** [comment]
The short version is that the [AEM Brackets Plugin](https://github.com/Adobe-Marketing-Cloud/aem-brackets-extension) uses _AEM specific_ APIs to push micro content packages based on local file changes.

There's definitely a need for some sort of front-end sync, but it's a bit out of the scope of the Slick project. A Sling-specific tool should be built to sync file changes. A clever node/curl wrapper around the SlingPostServlet API. Something tied directly into Jackrabbit / Oak could also be a possibility.

That being said, HTL / Sightly changes _**will**_ sync if you use the Eclipse Sling Plugin. Originally I wanted to keep the JS / SCSS stack simple to allow for sync through Eclipse, but it didn't scale as front-end needs became more complex.

**Comment by chrismade** [comment]
thanks for this excellent and quick answer! I will close the issue now, maybe you want to copy it into the wiki here on github or your blog just in case some else has the same question

**Comment by auniverseaway** [comment]
Ask and Ye shall receive.

I found an NPM package that does exactly what I suggested... cURL's a file to Sling. I've added it to the default gulp task. If you have gulp setup, you can just run 'gulp' in  ui.apps, make your changes to either SCSS or JS, and it will send it to Sling.

I've updated the [README](https://github.com/auniverseaway/slick-2/blob/master/README.md) to reflect this process. Let me know if you run into any issues!

**Comment by chrismade** [comment]
thanks, Chris, again  - and sorry, I was a bit too fast and optimistic asking the brackets / gulp question ... because I'm still struggling to get slick-21 up and running in AWS so I need to focus on this part first before I consider any frontend adaptions

**Comment by auniverseaway** [comment]
Hmm, what are you struggling with on AWS? I can likely help you get it resolved.

**Comment by chrismade** [comment]
thanks for your help - I will open a new "issue" (rather request for help) - let's see
